name: 'Get rust project version'
author: 'breadrock1'
description: 'Current GitHub actions provides ability to get rust project version. This action useful to create release and upload artifacts.'

inputs:
  manifest-path:
    description: 'Cargo.toml manifest file path'
    required: true
    default: 'Cargo.toml'

outputs:
  project-version:
    description: 'There is rust project version'

runs:
  using: 'composite'
  steps:
    - name: Run the shell script
      id: get-version
      shell: bash
      run: |
        chmod +x get-version.sh
        
        echo "${{ outputs.project-version }}"
        
        # Execute the script and capture its output
        ./get-version.sh "${{ inputs.manifest-path }}"
        
        echo "${{ outputs.project-version }}"
