name: get-rust-project-version

on:
  push:
    branches:
      - "master"

jobs:
  check-action-processing:
    runs-on: ubuntu-latest

    outputs:
      version_output: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get-version
        uses: breadrock1/rust-project-version@v0.2
        with:
          manifest-path: 'example/hello-world/Cargo.toml'

      - name: Check version is valid
        run: |
          echo "${{ steps.get-version.outputs.version }}"
          [ "${{ steps.version.outputs.version }}" = "0.1.0" ] && echo 'is valid version'
