name: get-rust-project-version

on:
  push:
    branches:
      - "master"

jobs:
  check-action-processing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get-project-version
        uses: breadrock1/rust-project-version@v0.6
        with:
          manifest-path: 'example/hello-world/Cargo.toml'

      - name: Check version is valid
        run: |
          echo "${{ steps.get-project-version.outputs }}"
          echo "${{ steps.get-project-version.outputs.project-version }}"
          echo "${{ toJson(steps.get-project-version.outputs) }}"
          echo "${{ toString(steps.get-project-version.outputs) }}"
          [ "${{ steps.get-project-version.outputs.project-version }}" = "0.1.0" ] && echo 'is valid version'
